# ENTITY API

### List entities
GET http://localhost:8080/entities

### Create entities
POST http://localhost:8080/entities
Content-Type: application/json

{
  "name":"Phuc qua dep trai",
  "description":"Qua dep trai",
  "url":"phucdeptrai.com.vn"
}

### Read entity
GET http://localhost:8080/entities/5d12ebf18b61eb310189281f

### Update entity
POST http://localhost:8080/entities
Content-Type: application/json

{
  "name":"Phuc qua dep trai",
  "description":"Kha la banh",
  "url":"phucdeptrai.com.vn"
}

### Delete entity
DELETE  http://localhost:8080/entities/5d12ebf18b61eb310189281f

# USER API

### Sign up
POST http://localhost:8080/signup
Content-Type: application/json

{
  "user_name": "phucdeptrai",
  "password": "123456"
}

### Log in
POST http://localhost:8080/login
Content-Type: application/json

{
  "user_name": "phucdeptrai",
  "password": "123456"
}

### Log out
POST http://localhost:8080/logout
Content-Type: application/json

{
  "id" : "5e685c6a168de9eac88525e3"
}
